nats:
  url: nats://127.0.0.1:4222

consul:
  address: localhost:8500

mpc_threshold: 2
environment: development
badger_password: "wEZWAyT8HBoQLunVnsurtGSBudViLtRj"
event_initiator_pubkey: "05a547a2c4f3f4a1b2ddc3906196f3c34ddbfae7e0819ca3b6f68a0c59285456"
max_concurrent_keygen: 2
db_path: "."  
backup_enabled: true
backup_period_seconds: 300 # 5 minutes
backup_dir: backups
