badger_password: +TQ_=Iz^$R&G#2^PZ_3ojE+]2D6~\6$y
consul:
  address: localhost:8501
db_path: ./test_db
environment: development
event_initiator_pubkey: e42a14842c197a08af77e56b9fb8fae2e50316c3e51b51e14e6a7bf17c1ef77d
max_concurrent_keygen: 1
mpc_threshold: 2
mpcium_version: 1.0.0
nats:
  url: nats://127.0.0.1:4223
